name: Provision
description: Set up job with tasks needed to run a code check
runs:
  using: 'composite'
  steps:
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}

    - name: Install dependencies
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      run: yarn --frozen-lockfile
      shell: bash
