version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'pnpm'
    directory: '/'
    schedule:
      interval: 'daily'
    group:
      leather:
        applies-to: version-updates
        patterns:
          - '@leather-wallet/*'
