name: Build feature extensions
on: [pull_request, workflow_dispatch]

env:
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  pre-run:
    name: Cancel ongoing jobs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@ad6cb1b847ffb509a69b745b6ee2f1d14dfe14b8
        with:
          access_token: ${{ github.token }}

  update-pull-request-body:
    name: Add download links in PR body
    runs-on: ubuntu-latest
    needs:
      - pre-run
    steps:
      - uses: kyranjamie/pull-request-fixed-header@v1.0.1
        # Don't run on forks
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          header: '> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/${{ github.run_id }}).'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-wallet:
    # https://github.community/t/do-expressions-support-ternary-operators-to-change-their-returned-value/18114/4
    name: Build extension ${{ fromJSON('["unminified", "minified"]')[matrix.minified] }}
    strategy:
      matrix:
        minified: [true, false]
    env:
      MINIFY_PRODUCTION_BUILD: ${{ matrix.minified }}

    runs-on: ubuntu-latest
    needs:
      - pre-run
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Build project
        run: yarn build

      - name: Zip extension
        run: sh build-ext.sh

      - uses: actions/upload-artifact@v2
        with:
          name: hiro-wallet-${{ fromJSON('["unminified", "minified"]')[matrix.minified] }}
          path: hiro-wallet.zip

  upload-chromium-build:
    name: Upload Chromium preview assets
    runs-on: ubuntu-latest
    needs:
      - pre-run
      - build-wallet
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: hiro-wallet-unminified

      - uses: actions/upload-artifact@v2
        name: Upload Chromium Extension Zip
        with:
          name: hiro-wallet-chromium
          path: hiro-wallet.zip
          if-no-files-found: error

  upload-firefox-build:
    name: Upload Firefox preview assets
    runs-on: ubuntu-latest
    needs:
      - pre-run
      - build-wallet
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: hiro-wallet-minified

      - uses: actions/upload-artifact@v2
        name: Upload Firefox Extension Zip
        with:
          name: hiro-wallet-firefox
          path: hiro-wallet.zip
          if-no-files-found: error
