name: PR Extensions builds
on: [pull_request, workflow_dispatch]

jobs:
  pre-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@main
        with:
          access_token: ${{ github.token }}

  set-in-progress-message:
    if: github.repository == 'leather-wallet/extension' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Make short commit SHA
        run: echo "SHORT_SHA=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-7`" >> $GITHUB_ENV

      - uses: kyranjamie/pull-request-fixed-header@v1.0.1
        with:
          header: '> _Building Leather at commit `${{ env.SHORT_SHA }}`_'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: build-${{ matrix.target }}-extension
    runs-on: ubuntu-latest
    needs:
      - pre-run
    strategy:
      matrix:
        target: [chromium, firefox]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: ./.github/actions/provision

      - run: echo "SHORT_SHA=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-7`" >> $GITHUB_ENV

      - name: Build project
        run: yarn build
        env:
          WALLET_ENVIRONMENT: feature
          TARGET_BROWSER: ${{ matrix.target }}
          COINBASE_APP_ID: ${{ secrets.COINBASE_APP_ID }}
          MOONPAY_API_KEY: ${{ secrets.MOONPAY_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SEGMENT_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_KEY_STAGING }}
          TRANSAK_API_KEY: ${{ secrets.TRANSAK_API_KEY }}
          PR_NUMBER: ${{ github.event.number }}
          COMMIT_SHA: ${{ env.SHORT_SHA }}

      - uses: actions/upload-artifact@v3
        name: Upload ${{ matrix.target }} Extension Zip
        with:
          name: leather-${{ matrix.target }}-${{ env.SHORT_SHA }}
          path: dist

  set-download-link:
    if: github.repository == 'leather-wallet/extension' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs:
      - pre-run
      - build
    steps:
      - uses: kyranjamie/pull-request-fixed-header@v1.0.1
        with:
          header: '> Try out this version of Leather — [download extension builds](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
