name: Chromatic

on: [pull_request, workflow_dispatch]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: yarn

      - uses: chromaui/action@latest
        with:
          autoAcceptChanges: 'main'
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
