name: GH pages

on:
  push:
    branches:
      - 'main'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/provision

      - name: Build
        run: yarn test:coverage

      - name: Make badge maker
        run: npx make-coverage-badge

      - name: Publish test coverage report
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: coverage
