name: Mirror dev to beta

on:
  push:
    branches: [dev]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Reset beta branch to dev
        uses: nicksnell/action-reset-repo@master
        with:
          reset_branch: beta
          base_branch: dev
          github_token: ${{ secrets.GH_TOKEN }}
