name: Publish Dev Extensions
on:
  push:
    tags:
      - 'v*dev*'
  workflow_dispatch:

env:
  # To use another sentry DSN
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  PREVIEW_RELEASE: true
  WALLET_ENVIRONMENT: preview

jobs:
  build-extension:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1

      - name: Build project
        env:
          IS_PUBLISHING: true
        run: yarn build

      - uses: actions/upload-artifact@v2
        name: Upload build artifact
        with:
          name: hiro-wallet
          path: dist

  create-github-release:
    name: Create Github release
    runs-on: ubuntu-latest
    needs:
      - build-extension
    steps:
      - name: Download extension build
        uses: actions/download-artifact@v2
        with:
          path: .

      - name: Download release-notes.txt from create-version workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create-version.yml
          name: release-notes

      - run: ls -R

      - name: Zip release build
        run: zip -r hiro-wallet.v${{ needs.build-extension.outputs.new_version }}.zip hiro-wallet/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: v${{ needs.build-extension.outputs.new_version }}
          body_path: release-notes.txt
          files: hiro-wallet.v${{ needs.build-extension.outputs.new_version }}.zip
