name: Version
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  COMMIT_USER: Hiro DevOps
  COMMIT_EMAIL: 45208873+blockstack-devops@users.noreply.github.com

jobs:
  pre-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@ad6cb1b847ffb509a69b745b6ee2f1d14dfe14b8
        with:
          access_token: ${{ github.token }}

  version:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'Version release'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install packages
        uses: ./.github/actions/provision
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Create Release Pull Request
        uses: changesets/action@640c4a5d646991720131ef3b6e0e63220de5dddf
        with:
          title: "[RELEASE] Version extension"
          commit: 'Version release'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
